name: MCGraphPlot
version: '${project.version}'
main: io.github.quietsato.mcgraphplot.MCGraphPlot
api-version: 1.18

commands:
  graphplot:
    usage:
      /graphplot [equation]
    aliases:
      - gp
